codecov:
  # require_ci_to_pass: yes
  require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: auto
        # don't fail for tiny decreases in project-level coverage, rely on
        # patch coverage to maintain overall levels
        threshold: 1%
#   precision: 2
#   round: down
#   range: "70...100"

# parsers:
#   gcov:
#     branch_detection:
#       conditional: yes
#       loop: yes
#       method: no
#       macro: no

# comment:
#   layout: "reach,diff,flags,tree"
#   behavior: default
#   require_changes: no

ignore:
  # mocks are test code, don't care about coverage there
  # go reports coverage names package qualified, important for the ignore
  - ".*/internal/mocks/"
  - ".*/internal/networking/mocks/"
  - ".*_test.go$"
