# cSpell: disable

linters:
  enable:
    - gocyclo
    - gofmt
    - goimports
    - gofumpt
    - revive
    - misspell
    - prealloc
    - stylecheck
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: "superfluous-else"
        disabled: true
  gofumpt:
    extra-rules: true

issues:
  # disable default rule suppressions,
  # esp. for the "exported methods must have a comment" bit
  exclude-use-default: false
  exclude-dirs:
    - try

  # emit more hits to the same linter rule at once than the default
  max-same-issues: 10

  # ... but we need to turn some back on
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
