version: "2"
linters:
  enable:
    - gocyclo
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 20
    revive:
      rules:
        - name: superfluous-else
          disabled: true
  exclusions:
    generated: lax
    rules:
      - path: "(.+)\\.go$"
        # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
        text: Error return value of .((os\.)?Std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Unsetenv|Setenv)). is not checked
        linters:
          - errcheck
    paths:
      - try
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 10
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - try
      - third_party$
      - builtin$
      - examples$
