#!/bin/sh

if [ -d /run/systemd/system ]; then
	# TODO: this bit is dpkg specific, make it work for RPMs too?
	if [ "$1" = "remove" ]; then
		echo "Stopping wirelink units..."
		systemctl --system stop 'wl-quick@*' 'wirelink@*'
	fi
fi
