name: Go Fuzz
on: [push]
concurrency:
  group: fuzz-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  fuzz:
    name: fuzz
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24"
        id: go

      - name: Get tags to make version.go
        run: |
          git fetch origin +refs/tags/*:refs/tags/*
          d=30
          while ! go tool mage info ; do
            git fetch --deepen=$d origin +refs/tags/*:refs/tags/*
            d=$((d+10))
          done

      - name: Run fuzz tests
        run: go tool mage test:fuzz
