name: Go Fuzz
on: [push]
concurrency:
  group: fuzz-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  fuzz:
    name: fuzz
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.25.0-rc.1"
        id: go

      - name: Get tags to make version.go
        run: |
          go tool mage deepen

      - name: Run fuzz tests
        run: go tool mage test:fuzz
