name: Go
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-13
          - macos-14
          # macos-15 is arm
          - macos-15
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24"
        id: go

      - name: Get tags to make version.go
        run: |
          git fetch origin +refs/tags/*:refs/tags/*
          d=30
          while ! go tool mage info ; do
            git fetch --deepen=$d origin +refs/tags/*:refs/tags/*
            d=$((d+10))
          done

      - name: Get dependencies
        run: |
          go mod download -x
      - name: Get tools
        run: |
          git diff --exit-code
          go mod tidy
          git diff --exit-code

      - name: Build
        run: |
          go tool mage compile
          go mod tidy
          git diff --exit-code

      - name: Format check
        run: |
          go tool mage lint:fix
          git diff --exit-code

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: govulncheck
        run: go tool mage lint:vulncheck

      - name: Test with coverage
        # building the coverage output runs the tests
        run: go tool mage test:cover
      - name: Generate coverage report
        # even if tests fail, generate the report
        if: ${{ always() }}
        run: go tool mage test:coverHTML
      # upload to codecov as soon as we can to view reports
      - name: Upload coverage (codecov)
        if: ${{ always() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true
          files: ./coverage.out
          fail_ci_if_error: true
      - name: Upload coverage (artifact)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.1
        with:
          name: coverage-${{ matrix.os }}.html
          path: ./coverage.html

      - name: Test with race detector
        # combination of macos runners being slow and race detector messing with
        # timing makes this combination too flaky for now
        if: "!startsWith(matrix.os, 'macos-')"
        run: go tool mage test:goRace
