name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULEE: "on"
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Record go env
      run: |
        go env

    - name: Get dependencies
      run: |
        set -x
        go get -v -t -d ./...
        cd /tmp
        go get golang.org/x/lint/golint
        go get golang.org/x/tools/gopls@latest

    - name: Lint
      #run: go build -v .
      run: make vet lint

    - name: Build
      #run: go build -v .
      run: make compile

    - name: Test
      run: make test-go coverage.html

    - name: Upload coverage
      uses: actions/upload-artifact@v1.0.0
      with:
        name: coverage.html
        path: ./coverage.html
